export let books = [
  {
    id: 1,
    title: 'Название книги',
    author: 'Автор книги',
    description: '',
    pageCount: '',
    price: '555',
    img: 'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
  },
  {
    id: 2,
    title: 'Название книги',
    author: 'Автор книги',
    description: '',
    pageCount: '',
    price: '111',
    img: 'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
  },
  {
    id: 3,
    title: 'Название книги',
    author: 'Автор книги',
    description: '',
    pageCount: '',
    price: '333',
    img: 'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
  },
  {
    id: 4,
    title: 'Название книги',
    author: 'Автор книги',
    description: '',
    pageCount: '',
    price: '444',
    img: 'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
  },
  {
    id: 5,
    title: 'Название книги',
    author: 'Автор книги',
    description: '',
    pageCount: '',
    price: '',
    img: 'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
  },
]
